### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by lkwirica** [intrahealth/emNutt#22]
Introduce a feature to handle various creation of users in order to manage access and security of the platform. Consider the following rights:

Overall Administrator/mHero overall admin (Developer)-can create users and user admin, cannot be disabled, cannot be deleted 

System Administrator (HRH Kenya Admin/MoH Admin) -Can create and edit,and archive/disable users but cannot create, edit or diable/archive  overall admin 

Other users-cannot create edit or achive other users,can edit own password

**Comment by cloehr651** [comment]
This is a great suggestion. Unless this is super easy to do (maybe since this has been added to iHRISv5 with the implementation in Ethiopia? @ashaban please weigh in) I would recommend making this lower priority so that we can make sure everything is functioning as we want it to before introducing it to new users.

**Comment by ashaban** [comment]
this will be handled in iHRIS V

**Comment by ashaban** [comment]
this has been fixed @lkwirica

**Comment by njugunask** [comment]
It is not possible to add a user gives below error
<img width="942" alt="User roles-errors" src="https://user-images.githubusercontent.com/77440202/122363222-75333680-cf61-11eb-8ccc-3957060c0446.png">

Is it possible to define or list the roles that can be assigned as per the request for specific users? For example, if it's the User -  Overall Admin, one can then choose from the list the roles for this user.

**Comment by nobertmn** [comment]
@ashaban I have posted a fix for this in the main iHRIS. Review and let me know if more needs to be done.

**Comment by njugunask** [comment]
There is still an error when trying to save
<img width="949" alt="User Mgt Test error" src="https://user-images.githubusercontent.com/77440202/122525972-78422b80-d022-11eb-9903-e1d5f76809fb.png">

**Comment by lkwirica** [comment]
![image](https://user-images.githubusercontent.com/77771356/122704653-c6db0a00-d25c-11eb-824c-8b1ef666633c.png)
You cannot successfully create a new role

**Comment by cloehr651** [comment]
@ashaban and @njugunask is this done now?

**Comment by njugunask** [comment]
@cloehr651, this is still in progress, not all user requests have been implemented
